project:
  type: manuscript

manuscript:
  article: article.qmd
  code-links: repo

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

execute:
  freeze: true
